# Generated by Django 5.2.12 on 2026-04-02 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0005_bloqueotour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='flow', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Amount in minor units (e.g. CLP pesos).')),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('provider_token', models.CharField(blank=True, max_length=120, null=True)),
                ('provider_order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_create_response', models.JSONField(blank=True, null=True)),
                ('raw_confirm_payload', models.JSONField(blank=True, null=True)),
                ('raw_status_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha de borrado lógico', null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tours.tour')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_token'], name='payments_pa_provide_670d26_idx'), models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'), models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx')],
            },
        ),
    ]
