# Generated by Django 5.2.12 on 2026-04-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_customer_email_payment_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tour_nombre_al_pagar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='tour_precio_al_pagar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Adulto Histórico'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tour_precio_nino_al_pagar',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Precio Niño Histórico'),
        ),
    ]
