[phases.setup]
nixPkgs = ["python311", "nodejs_22", "gcc", "postgresql"]

[phases.install]
# Instalamos dependencias de Node y Python
cmds = [
    "npm install",
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
# Primero compilamos Tailwind 4 y luego recolectamos estáticos
cmds = [
    "npm run build", 
    "/opt/venv/bin/python manage.py collectstatic --noinput"
]

[start]
# Usamos el Gunicorn que está dentro del entorno virtual
cmd = "/opt/venv/bin/python -m gunicorn config.wsgi --bind 0.0.0.0:$PORT --timeout 600"