[phases.setup]
nixPkgs = ["python311", "gcc", "postgresql"]

[phases.install]
# Instalamos TODO junto para que quede en el mismo PATH
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
# Primero el frontend, luego los estáticos de Django
cmds = ["npm run build", "python manage.py collectstatic --noinput"]