# Generated by Django 6.0.2 on 2026-03-03 12:16

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del tipo (opcional)')),
            ],
            options={
                'verbose_name': 'Categoría de Tour',
                'verbose_name_plural': 'Categorías de Tours',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('itinerario', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Itinerario Detallado')),
                ('incluye', models.TextField()),
                ('video_youtube', models.URLField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(upload_to='tours/principales/')),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='tours.tipotour', verbose_name='Tipo de Tour')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_adulto', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio Adulto/General (CLP)')),
                ('tiene_precio_nino', models.BooleanField(default=False, verbose_name='¿Activar precio para niños?')),
                ('valor_nino', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, verbose_name='Precio Niño (CLP)')),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='precio', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Precio de Tour',
                'verbose_name_plural': 'Precios de Tours',
            },
        ),
        migrations.CreateModel(
            name='GaleriaTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tours/galeria/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='tours.tour')),
            ],
        ),
    ]
