# Generated by Django 6.0.2 on 2026-03-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Si se marca, aparecerá en la sección principal de la página de inicio.', verbose_name='Destacado'),
        ),
    ]
