# Generated by Django 6.0.2 on 2026-03-13 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrado_el', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Fecha de borrado')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono/WhatsApp')),
                ('fecha', models.DateField(verbose_name='Fecha del tour')),
                ('adultos', models.PositiveIntegerField(default=1, verbose_name='Número de adultos')),
                ('ninos', models.PositiveIntegerField(default=0, verbose_name='Número de niños (hasta 11 años)')),
                ('precio_total', models.IntegerField(editable=False, verbose_name='Precio Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la reserva')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas internas (Clima, Vehículo, Disponibilidad)')),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
                ('actualizada_el', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha'],
            },
        ),
    ]
