# Generated by Django 6.0.2 on 2026-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha', '-creada_el'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Confirmación'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='notas_internas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas (Vehículo, Clima, etc.)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_total',
            field=models.IntegerField(editable=False, verbose_name='Precio Total ($)'),
        ),
    ]
