# Generated by Django 5.2.12 on 2026-03-26 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_reserva_options_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Bloqueo de Fecha',
                'verbose_name_plural': 'Bloqueos de Fechas',
                'unique_together': {('tour', 'fecha')},
            },
        ),
    ]
