# Generated by Django 5.2.12 on 2026-04-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_bloqueotour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
    ]
