# Generated by Django 5.2.12 on 2026-08-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_terceraedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='es_prueba',
            field=models.BooleanField(default=False, help_text='Si se marca, el tour NO aparecerá en el listado público aunque esté activo. Solo accesible por URL directa.', verbose_name='Tour de prueba'),
        ),
    ]
