# Generated by Django 5.2.12 on 2026-09-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_add_tour_es_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Código de reserva'),
        ),
    ]
