# Generated by Django 5.2.12 on 2026-10-06 17:19

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_reserva_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='itinerario',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Resumen del tour'),
        ),
        migrations.CreateModel(
            name='ItinerarioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=1, verbose_name='Día')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del día')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Día del itinerario',
                'verbose_name_plural': 'Itinerario por día',
                'ordering': ['orden', 'pk'],
            },
        ),
    ]
