# Generated by Django 5.2.12 on 2026-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_itinerariodia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='mapa',
            field=models.ImageField(blank=True, null=True, upload_to='tours/mapas/', verbose_name='Mapa del tour'),
        ),
    ]
