# Generated by Django 5.2.12 on 2026-10-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_tour_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='incluye',
            field=models.TextField(blank=True),
        ),
    ]
