# Generated by Django 5.2.12 on 2026-10-06 19:24

import ckeditor_uploader.fields
from django.db import migrations
from django.utils.html import linebreaks


def texto_a_html(apps, schema_editor):
    """«Incluye» era texto plano: se pasa a HTML para conservar los saltos de línea."""
    Tour = apps.get_model('tours', 'Tour')
    for t in Tour.objects.exclude(incluye=''):
        if '<' not in t.incluye:
            Tour.objects.filter(pk=t.pk).update(incluye=linebreaks(t.incluye))


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_incluye_opcional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='incluye',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Incluye'),
        ),
        migrations.RunPython(texto_a_html, migrations.RunPython.noop),
    ]
