# Generated by Django 6.0.2 on 2026-03-09 15:16

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Reseña')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('extracto', models.TextField(help_text='Pequeño resumen para la lista de blogs.', max_length=500)),
                ('contenido', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Cuerpo de la reseña')),
                ('imagen_portada', models.ImageField(upload_to='blog/portadas/', verbose_name='Imagen Principal')),
                ('video_youtube', models.URLField(blank=True, help_text='Opcional: Pega la URL completa del video (ej: https://www.youtube.com/watch?v=...)', max_length=500, null=True, verbose_name='Enlace de YouTube')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
