# Generated by Django 5.2.12 on 2026-06-17 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_imagencarousel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='blog/post_images/', verbose_name='Imagen')),
                ('despues_del_parrafo', models.PositiveIntegerField(default=1, help_text='Número del párrafo tras el cual aparece esta imagen (1 = después del 1°). Usa 0 para insertarla antes de todo el contenido.', verbose_name='Después del párrafo')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Pie de foto')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Si hay varias imágenes en la misma posición, cuál va primero.', verbose_name='Orden')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_post', to='blog.post')),
            ],
            options={
                'verbose_name': 'Imagen entre párrafos',
                'verbose_name_plural': 'Imágenes entre párrafos',
                'ordering': ['despues_del_parrafo', 'orden'],
            },
        ),
    ]
