# Generated by Django 5.2.12 on 2026-09-25 11:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False, verbose_name='Activo')),
                ('mensaje', ckeditor_uploader.fields.RichTextUploadingField(default='Estamos realizando tareas de mantención. Vuelve pronto.', verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Modo Mantención',
                'verbose_name_plural': 'Modo Mantención',
            },
        ),
    ]
