"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tu_53-at5s0jw-&9hkvp+c-%n+rzar(+59pxh!jckw7f!*x!dt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'debug_toolbar',
    'jet',
    'jet.dashboard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ckeditor',
    'ckeditor_uploader',

    #APP ORANGE TRAVEL
    'home',
    'tours',
    'blog'
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

INTERNAL_IPS = [
    "127.0.0.1",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'django.contrib.messages.context_processors.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'orage_db',
        'USER': 'cesar',
        'PASSWORD': 'qwedsa',
        'HOST': '127.0.0.1',
        'PORT': 5432
    }
}



# DJANGO JET

# Temas disponibles: 'default', 'green', 'light-violet', 'red', 'yellow'
# JET_DEFAULT_THEME = 'light-violet' # Prueba este para un look más moderno
# JET_SIDE_MENU_COMPACT = True


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cl'


TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Busca archivos aquí en desarrollo
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar': 'Custom',
        'height': 600,
        'width': '100%',
        'language': 'es',
        'extraAllowedContent': 'img(*); div(*); figure(*); figcaption(*);',
        # 'image2' es el secreto para que se parezca a WordPress
        'extraPlugins': ','.join(['image2', 'uploadimage', 'widget', 'lineutils', 'clipboard', 'dialog', 'dialogui']),
        'removePlugins': 'image', # Quitamos el plugin de imagen viejo
        

        'disallowedContent': 'img{width,height}[width,height]', # Prohíbe anchos fijos
        'extraConfig': {
            'image2_disableResizer': True, # Evita que el usuario estire la imagen a mano
        },
        'contentsCss': [
            'https://cdn.tailwindcss.com', # Opcional: para que entienda clases base
            '/static/css/output.css',      # <--- TU ARCHIVO COMPILADO
        ],
        # 2. Le decimos que el "cuerpo" del editor debe tener la clase que creamos
        # Esto es vital para que las reglas de ".resena-content .img-blog-small" funcionen
        'bodyClass': 'resena-content',
        
        'toolbar_Custom': [
            ['Styles', 'Format', 'FontSize'], # <--- Asegúrate de tener 'Styles'
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'], # Alineación de texto
            ['Link', 'Unlink'],
            ['Image', 'Table', 'HorizontalRule', 'SpecialChar'], # El botón de imagen ahora usará 'image2'
            ['TextColor', 'BGColor'],
            ['Maximize', 'Source'],
        ],
        # Configuración específica para que las imágenes se porten bien
        'image2_alignClasses': ['image-left', 'image-center', 'image-right'],
        'image2_captionedClass': 'image-captioned',

    # 2. Definimos qué hace cada estilo
'stylesSet': [
            # PRUEBA DE TEXTO: Selecciona una palabra y mira si aparece esto
            {
                'name': 'Texto Alerta Naranja',
                'element': 'span',
                'attributes': { 'class': 'text-orange-500 font-bold' }
            },
            # ESTILOS DE IMAGEN (Optimizados para Image2)
            {
                'name': 'Imagen Pequeña (25%)',
                'element': 'img',
                'attributes': { 'class': 'img-blog-small' },
                'type': 'widget', 'widget': 'image' # <--- Esto le dice que es un widget de imagen
            },
            {
                'name': 'Imagen Mediana (50%)',
                'element': 'img',
                'attributes': { 'class': 'img-blog-medium' },
                'type': 'widget', 'widget': 'image'
            },
            {
                'name': 'Imagen Full (100%)',
                'element': 'img',
                'attributes': { 'class': 'img-blog-full' },
                'type': 'widget', 'widget': 'image'
            },
        ],

    },
}

CKEDITOR_UPLOAD_PATH = "publicaciones/" # Se guardará dentro de /media/uploads/
# 1. Carpeta dentro de 'media' donde se guardarán las fotos del editor

# 2. Motor de procesamiento de imágenes (asegúrate de tener 'Pillow' instalado)
CKEDITOR_IMAGE_BACKEND = "pillow"

# 3. (Opcional) Restringe que solo usuarios staff puedan subir archivos
CKEDITOR_RESTRICT_BY_USER = True
# Asegúrate de que el nombre del archivo sea exactamente dashboard.py en la raíz
# JET_INDEX_DASHBOARD = 'dashboard.CustomIndexDashboard'
# JET_APP_INDEX_DASHBOARD = 'dashboard.CustomAppIndexDashboard'

SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'